#!/usr/bin/env bash
set -u
cd /root/autodl-tmp/PAFT

log() { echo "[finisher] $* $(date -Is)"; }

log "waiting for supervisor to finish all validators"
while ! grep -q "all validators finished" logs/e5_supervisor.log 2>/dev/null; do
  sleep 120
done

log "validation complete; running report"
OUT="analysis_outputs/tse_revision_e5_prompt_variants.md"

{
  echo "# E5: prompt-variant baselines (base DS-Coder-6.7B, no fine-tuning)"
  echo
  echo "Generated by scripts/e5_prompt_variants_generate.py and validated by test_d4j.py."
  echo
  echo "Variants: plain (shared prompt), minimal (paper PROMPTING wording), emphatic"
  echo "(stronger minimal-edit instruction), fewshot (emphatic + one worked example)."
  echo
  echo "Metrics: pass@1 = mean plausible/10 over 371 faults; AED = char Levenshtein(buggy,"
  echo "candidate); CCR = matching-line fraction; over-editing ratio ="
  echo "Levenshtein(buggy, candidate) / Levenshtein(buggy, developer fix)."
  echo
  /root/miniconda3/envs/paft/bin/python scripts/e5_report.py --root . \
    --set "Base (plain, rerun)=defects4j/results/prompting-plain-rerun" \
    --set "Prompting (minimal, rerun)=defects4j/results/prompting-minimal" \
    --set "Prompting (emphatic)=defects4j/results/prompting-emphatic-rerun" \
    --set "Prompting (fewshot)=defects4j/results/prompting-fewshot" \
    --set "PAFT (paper)=defects4j/results/deepseek-6.7b-paft" \
    --set "Base (paper)=defects4j/results/deepseek-6.7b" \
    --set "SFT (paper)=defects4j/results/deepseek-6.7b-promptloss" \
    --set "Prompting (paper)=defects4j/results/deepseek-6.7b-prompting"
} > "$OUT" 2>&1

log "report written to $OUT"
cat "$OUT"
